apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: doppler-injector-webhook-deployment
  namespace: doppler-injector
  labels:
    app: doppler-injector
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: doppler-injector
    spec:
      containers:
        - name: doppler-injector
          image: okteto/doppler-injector:0.2
          imagePullPolicy: IfNotPresent
          env:
            - name: API
              valueFrom:
                secretKeyRef:
                  name: doppler-injector-secret
                  key: api
            - name: PIPELINE
              valueFrom:
                secretKeyRef:
                  name: doppler-injector-secret
                  key: pipeline
            - name: ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: doppler-injector-secret
                  key: environment
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: doppler-injector-webhook-certs
