apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        injector.doppler.com/inject: "yes"
        injector.doppler.com/pipeline: "194"
        injector.doppler.com/environment: "dev_ramiro"
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: nginx:alpine
        imagePullPolicy: IfNotPresent