apiVersion: v1
kind: Service
metadata:
  name: doppler-injector-webhook-svc
  namespace: doppler-injector
  labels:
    app: doppler-injector
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: doppler-injector
