
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-injector
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: doppler-injector
    spec:
      terminationGracePeriodSeconds: 0
      volumes:
        - name: shared-data
          emptyDir: {}
      initContainers:
      - image: dopplerhq/injector:0.1.0
        name: doppler
        volumeMounts:
          - name: shared-data
            mountPath: /var/secret/doppler
        env:
          - name: DOPPLER_API_KEY
            value: "<API Key>"
          - name: DOPPLER_PIPELINE
            value: "<Pipeline ID>"
          - name: DOPPLER_ENVIRONMENT
            value: "<Environment Name>"
      containers:
      - image: dopplerhq/sample:latest
        name: main
        volumeMounts:
          - name: shared-data
            mountPath: /var/secret/doppler
            readOnly: true
        command: 
        - sh
        - -c
        - source /var/secret/doppler/.env && yarn start
